info:
  namespace: gyakuten_saiban
items:
  #律师微章
  attorney_badge:
    enabled: true
    display_name: 律师微章
    lore:
    - '一斤鸭梨!'
    events:
      interact:
        right:
          execute_commands:
            cmd1:
              command: 'iaplaytotemanimation gyakuten_saiban:yiyi {player} silent'
              as_console: true
          play_sound:
            name: gyakuten_saiban:objection
            volume: 1
            pitch: 2
        right_shift:
          execute_commands:
            cmd1:
              command: 'iaplaytotemanimation gyakuten_saiban:yiyi {player} silent'
              as_console: true
          play_sound:
            name: gyakuten_saiban:objection
            volume: 1
            pitch: 1
        left_shift:
          execute_commands:
            cmd1:
              command: 'iaplaytotemanimation gyakuten_saiban:yiyi {player} silent'
              as_console: true
          play_sound:
            name: gyakuten_saiban:objection1
            volume: 1
            pitch: 1
        left:
          execute_commands:
            cmd1:
              command: 'iaplaytotemanimation gyakuten_saiban:yiyi {player} silent'
              as_console: true
          play_sound:
            name: gyakuten_saiban:objection1
            volume: 1
            pitch: 2
    resource:
      material: WHITE_DYE
      generate: true
      custonmodeldata: 9000000
      textures:
        - items/attorney_badge
    permission: gyakuten_saiban_attorney_badge

  #成步堂龙一的手
  phoenix_wright_hand:
    enabled: true
    display_name: 成步堂龙一的手
    lore:
    - '右键其他玩家可对其异议'
    - '同时对方也会收到异议的特效'
    events:
      interact:
        entity:
          execute_commands:
            cmd1:
              command: 'iaplaytotemanimation gyakuten_saiban:yiyi {player} silent'
              as_console: true
            cmd2:
              command: 'iaplaytotemanimation gyakuten_saiban:yiyi {target-player} silent'
              as_console: true
          play_sound:
            name: gyakuten_saiban:objection
            volume: 1
            pitch: 2
    resource:
      material: WHITE_DYE
      generate: true
      custonmodeldata: 9000001
      textures:
        - items/phoenix_wright_hand
    permission: gyakuten_saiban_phoenix_wright_hand

  #异议效果
  yiyi:
    enabled: true
    display_name: 异议(用于效果)
    resource:
      material: TOTEM_OF_UNDYING
      generate: true
      custonmodeldata: 9000002
      textures:
        - particles/yiyi
    permission: gyakuten_saiban_yiyi

categories:
  gyakuten_saiban:
    enabled: true
    skip_if_already: false
    icon: gyakuten_saiban:attorney_badge
    name: 逆转裁判
    permission: gyakuten_saiban_categories
    items:
      - gyakuten_saiban:attorney_badge
      - gyakuten_saiban:phoenix_wright_hand
      - gyakuten_saiban:yiyi